apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springkafka
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: springkafka
      annotations:
        ad.datadoghq.com/back.logs: '[{"source": "java", "service": "springkafka", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    spec:
      containers:
      - image: pejdd/springkafka:v0
        imagePullPolicy: Always
        name: springkafka
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
          - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: springkafka
spec:
  type: LoadBalancer
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app: springkafka
