apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }} 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Values.kafka.labels.name }}
    spec:
      containers:
      - env:
        - name: ENABLE_AUTO_EXTEND
          value: "true"
        - name: KAFKA_RESERVED_BROKER_MAX_ID
          value: "999999999"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "{{ .Values.kafka.name }}"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {{ .Values.zookeeper.name }}:2181
        name: {{ .Values.kafka.name }}
        image: wurstmeister/kafka
        ports:
        - containerPort: {{ .Values.kafka.port }}
