apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name }}
  labels:
    name: {{ .Values.kafka.labels.name }} 
spec:
  ports:
  - name: kafka-port
    port: {{ .Values.kafka.port }}
    protocol: TCP
  selector:
    name: {{ .Values.kafka.labels.name }}
