{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "springkafka.serviceAccountName" . }}
  labels:
{{ include "springkafka.labels" . | indent 4 }}
{{- end -}}
