name: Build and Deploy to GKE

on:
  push:
    branches:
    - dockerpull

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: pejman-sncf-cluster-1   # TODO: update to cluster name
  GKE_ZONE: europe-west3-a  # TODO: update to cluster zone
  DH_PWD: ${{ secrets.DOCKERHUB_PWD }}
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    #- name: Setup gcloud cli  
    #  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #  with:
    #    version: '290.0.1'
    #    service_account_key: ${{ secrets.GKE_SA_KEY }}
    #    project_id: ${{ secrets.GKE_PROJECT }}

    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    
    - name: Check environment
      run: |-
        pwd
        hostname
        id
        ls -lrt
        
    - name: Build jar
      run: |-
        gradle build
        
    - name: Build docker image to local registry 
      run: |-
        #docker login -u=pejdd -p=$DH_PWD
        docker build -f Dockerfile.springkafka -t springkafka .
        # Include docker push to docker hub   
    
